### ISSUE TITLE
A question about doctorai

### ISSUE THREAD

**Issue by XiaoLiuAI** [mp2893/doctorai#1]
Dr Edward Choi, I am very interested in your work about disease risk prediction, and I have a question about the experiment setting. You described in your paper that you tested the model performance on different prediction window. As I understand, the model is trained on the data setting of "using 18-6 months records to predict the risk for the future 6 months". 

**Would you use the data in prediction window for evaluation/testing?** 

Another question is about the negative examples(controls). 
"Up to 10 eligible primary care clinic-, sex-, and age-matched (in 5- year intervals) controls were selected for each incident HF case, yielding an overall ratio of 9 controls per case. Each control was also as- signed an index date, which was the HFDx timepoint of the matched case. Primary care patients were eligible to be controls if they did not meet the operational criteria for HF diagnosis prior to the HFDx timepoint plus 182 days of their corresponding case. Other details on matching are described in the supplementary section."

As I understand, the negative examples are patients that do not have heart failure in records, suppose we have a patient with records from 1990.1 - 1991.12 with heart failure diagnosis on 1991.6 and was 50 years old in 1991, one possible control can be a patient with records from 1985.1-1986.12 without heart failure and was also 50 years old in 1986. 

**How do we use the HFDx timepoint of the matched case?**

In addition, do you have any requirements about the frequency of diagnosis/number of codes in the observation periods? Too sparse (few codes) training data could make the model hard to converge and few information could be inefficient for prediction.

**Comment by mp2893** [comment]
Hi XiaoLiu,

I think your questions are related to my JAMIA paper, not Doctor AI.
In Doctor AI, I didn't change the observation/prediction window size.
I think I received another email from you with the same question, so I'll close this issue.

Thanks,
Ed
