### ISSUE TITLE
How to  recurrent your result which recall

### ISSUE THREAD

**Issue by jjl001** [mp2893/doctorai#3]
Hi Edward,

    I tune hyperparameters such as the number of RNN layers, the size of RNN and the size of embedding,However,the result is disappointed. The recall@30 is about 0.35.
    
    Therefore，first of all I want to recurrent your result.
    Could you give your pre-train model which was trained via Suffer Database? 
    I don't have Suffer Database, but I have MIMIC-III, MIMIC-II is a part of MIMIC-III, I can use the MIMIC-III in your pre-train. Maybe I can get a same result as in you paper

thank you very much!
jianglong

**Comment by mp2893** [comment]
Hi Jianglong,

It would be illegal for me to share a Doctor AI model trained on Sutter dataset with you, since the model is at least partially a property of Sutter Health.

Best,
Ed
