### ISSUE TITLE
Theano: We didn't implemented yet the case where scan do 0 iteration

### ISSUE THREAD

**Issue by sunilkalmadi** [mp2893/doctorai#7]
Hi Dr. Edward Choi, 
I have been following your work which I think is quite fascinating and impactful.

I am trying to implement Doctor AI using ICD codes on large scale population level data. However, currently I am facing following error:

`Loading data ...  done
Optimization start !!
Traceback (most recent call last):
  File "doctorAI.py", line 522, in <module>
    verbose=args.verbose
  File "doctorAI.py", line 448, in train_doctorAI
    cost = f_grad_shared(x, y, mask, lengths)
  File "/home/cvc2gpu16/anaconda3/envs/gct/lib/python2.7/site-packages/theano/compile/function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/cvc2gpu16/anaconda3/envs/gct/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/cvc2gpu16/anaconda3/envs/gct/lib/python2.7/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "/home/cvc2gpu16/anaconda3/envs/gct/lib/python2.7/site-packages/theano/scan_module/scan_op.py", line 963, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/cvc2gpu16/anaconda3/envs/gct/lib/python2.7/site-packages/theano/scan_module/scan_op.py", line 952, in p
    self, node)
  File "scan_perform.pyx", line 215, in theano.scan_module.scan_perform.perform
NotImplementedError: We didn't implemented yet the case where scan do 0 iteration
Apply node that caused the error: forall_inplace,cpu,gru_layer0}(Shape_i{0}.0, Elemwise{sub,no_inplace}.0, InplaceDimShuffle{0,1,x}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, IncSubtensor{InplaceSet;:int64:}.0, U_z_001, U_r_001, U_001, InplaceDimShuffle{x,0}.0, InplaceDimShuffle{x,0}.0, InplaceDimShuffle{x,0}.0)
Toposort index: 328
Inputs types: [TensorType(int64, scalar), TensorType(float64, (False, False, True)), TensorType(float64, (False, False, True)), TensorType(float64, 3D), TensorType(float64, 3D), TensorType(float64, 3D), TensorType(float64, 3D), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, row), TensorType(float64, row), TensorType(float64, row)]
Inputs shapes: [(), (0, 100, 1), (0, 100, 1), (0, 100, 200), (0, 100, 200), (0, 100, 200), (2, 100, 200), (200, 200), (200, 200), (200, 200), (1, 200), (1, 200), (1, 200)]
Inputs strides: [(), (800, 8, 8), (800, 8, 8), (160000, 1600, 8), (160000, 1600, 8), (160000, 1600, 8), (160000, 1600, 8), (1600, 8), (1600, 8), (1600, 8), (1600, 8), (1600, 8), (1600, 8)]
Inputs values: [array(0), array([], shape=(0, 100, 1), dtype=float64), array([], shape=(0, 100, 1), dtype=float64), array([], shape=(0, 100, 200), dtype=float64), array([], shape=(0, 100, 200), dtype=float64), array([], shape=(0, 100, 200), dtype=float64), 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown']
Outputs clients: [[Subtensor{int64:int64:int8}(forall_inplace,cpu,gru_layer0}.0, ScalarFromTensor.0, ScalarFromTensor.0, Constant{1}), Subtensor{int64:int64:int64}(forall_inplace,cpu,gru_layer0}.0, ScalarFromTensor.0, ScalarFromTensor.0, Constant{-1})]]
` 

I understand from Theano [forum](https://github.com/Theano/Theano/issues/4902) that the problem is that we have 0 iteration during recurence and Theano does not support that.  So, I wonder what  in Doctor AI code or my dataset is causing to end up with just 0 iteration. I think I have formatted the input files as described on Readme page. Some patients have only one event. Is that the issue here?

Your advice will be greatly appreciated.

OS: Ubuntu 16.04
Python 2.7
Theano 1.0.4
CUDA Version 10.1.243

Thank you,
Sunil

**Comment by mp2893** [comment]
Hi Sunil,

I suspect that maybe some of your samples have only one visit (i.e. sequence of length 1). Could you try again after removing those samples from your dataset?

Best
Ed

**Comment by sunilkalmadi** [comment]
Hi Ed,
Thanks for quick response.

Yes indeed, as I mentioned earlier, I have several patients with single visit (almost half of my dataset). However I was hoping to learn a model to predict readmissions (time and codes) for these patients with DoctorAI. Is it not possible in this framework? 

Meanwhile, I will report soon my progress after removing samples with single event. 
Thanks,
Sunil

**Comment by mp2893** [comment]
If you are training the model, then those with only 1 visit will either have no input or no label (depending on how you preprocessed the data) so the code won’t run. 
But if you are simply using a trained model for inference, then using samples with only 1 visit won’t cause problem.

**Comment by sunilkalmadi** [comment]
Thanks again. That clarifies a lot. 
But I have few more questions -

a) Can I keep single visit samples in .test file? or whether .test samples are also used in training the model?
(By general convention, my understanding is that only .train and .valid samples are used for training. Is that true here?)

b) For single visit samples, when visit and label files are same, is it the case of no input or no label?

c) Whether the integer substitutions used in place of medical codes have to start from zero ?

Thank you,
Sunil

**Comment by mp2893** [comment]
a) Yes the test files are used during the model training (please see line 462). So the test samples will go through the same preprocessing.

b) Yes. 

c) As long as there are sufficient embeddings to cover all medical codes, it doesn't matter that the mapping starts from 0. Note that the embeddings that are not mapped to actual medical codes will not be updated at all during training. So it's just waste of memory.

**Comment by sunilkalmadi** [comment]
Thank you for the answers!
